baseurl = "https://blist.vercel.app"
metaDataFormat = "yaml"
title = "ShahRiffy | Digital Garden"
theme = "blist"

#DefaultContentLanguage = "en"
#DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey! I'm Shahabor Hossain Rifat"
      introSubtitle = "Welcome to my digital garden. I’m passionate about  Security Research and Data Science . I write long-form essays as well as short notes about things I learned and sharing it publicly here."
      introPhoto = "/rifat2.jpg"
      logo = "/logo4.png"

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 1

    [[languages.en.menu.main]]
        name = "Essays"
        url = "blog"
        weight = 2

    [[languages.en.menu.main]]
        name = "Projects"
        url = "projects"
        weight = 3        

    [[languages.en.menu.main]]
        name = "Notes"
        url = "notes"
        weight = 4      

    [[languages.en.menu.main]]
        name = "Desk"
        url = "desk"
        weight = 5 





[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2024 - Shahabor Hossain Rifat · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system
[params.comments]
  # Supports disqus, giscus and utterances
  # Check hugo docs for setting up disqus
  system = "giscus"

  # Options for giscus, exclude hyphens
  repo = ""
  repoid = ""
  category = ""
  categoryid = ""
  mapping = ""
  strict = ""
  reactionsenabled = ""
  emitmetadata = ""
  inputposition = ""
  theme = ""

  # Options for utterances, exclude hyphens
  # repo = ""
  # issueterm = ""
  # theme = ""

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I share memes, blog posts, and tech tips."

[[params.homepage.social.icons]]
website = "twitter"
url = "https://twitter.com/ShahRiffy"
[[params.homepage.social.icons]]
website = "linkedin"
url = "https://linkedin.com/in/ShahRiffy"
[[params.homepage.social.icons]]
website = "github"
url = "https://github.com/ShahRiffy"
#[[params.homepage.social.icons]]
#website = "buymeacoffee"
#url = "https://www.buymeacoffee.com/"
[[params.homepage.social.icons]]
website = "medium"
url = "https://shahriffy.medium.com/"
[[params.homepage.social.icons]]
website = "stackoverflow"
url = "https://stackoverflow.com/users//ShahRiffy"
[[params.homepage.social.icons]]
website = "behance"
url = "https://behance.net/ShahRiffy"
[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
